### ISSUE TITLE
ErrorException

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#355] opened 2019-06-19 10:12 UTC
Failed method: `getproperty(::Any, ::Symbol)`

```
ErrorException:
   at getproperty(::Any, ::Symbol) (sysimg.jl18)
   at splitdrive(::String) (path.jl39)
   at splitdir (path.jl132)
   at process(::LanguageServer.JSONRPC.Request{Val{Symbol("textDocument/completion")},LanguageServer.CompletionParams}, ::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\requests\completions.jl26)
   at run(::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl47)
   at top-level scope (.\scripts\languageserver\main.jl22)
   at include (boot.jl326)
   at include_relative(::Module, ::String) (loading.jl1038)
   at include(::Module, ::String) (sysimg.jl29)
   at exec_options(::Base.JLOptions) (client.jl267)
   at _start() (client.jl436)
```

**Comment by ZacLN** [comment] 2019-07-09 20:57
Duplicate of https://github.com/julia-vscode/julia-vscode/issues/780

**Closed by ZacLN** 2019-07-09 20:57 UTC
Labels: bug
