### ISSUE TITLE
Could't retrieve cache file for multiple packages

### ISSUE THREAD

**Issue by andreichalapco** [julia-vscode/LanguageServer.jl#1151] opened 2022-09-04 16:59 UTC
Couldn't retrieve cache file for multiple packages: Base64, Logging, Printf ...

I'm currently using nvim with lsp (julials) and is pretty nerving not having those packages indexed in order to receive proper support. Every time I'm importing those packages I get than a missing reference error.

**Comment by fredrikekre** [comment] 2022-09-04 17:08
> Couldn't retrieve cache file for multiple packages

Probably duplicate of https://github.com/julia-vscode/SymbolServer.jl/issues/261 and nothing to worry about.

> Every time I'm importing those packages I get than a missing reference error.

Do you have them in your project file?

**Comment by andreichalapco** [comment] 2022-09-04 17:16
But that means the language server will not work properly ... I'm getting missing reference for PrintF or Random package for example

**Comment by fredrikekre** [comment] 2022-09-04 20:24
> Do you have them in your project file?

**Comment by andreichalapco** [comment] 2022-09-04 22:28
So I've been now using mason.nvim to install the LSP and before I always got some error:

```
[ERROR][2022-09-04 19:15:27] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"[ Info: Loading CSTParser from cache...\n"
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"ERROR: "
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"UndefVarError: FakeTypeofVararg not defined\nStacktrace:\n"
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"  [1] "
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"read("
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"io::"
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"IOStream, t::UInt8)\n    @ "
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"SymbolServer.CacheStore ~/.local/share/nvim/mason/packages/julia-lsp/scripts/packages/SymbolServer/src/"
[ERROR][2022-09-04 19:15:28] .../vim/lsp/rpc.lua:420	"rpc"	"julia-lsp"	"stderr"	"serialize.jl:"
```
But since then I've updated mason and it seems that everything is alright. I don't really knonw how the issue was fixed ...So we can close the issue.

**Closed** 2022-09-05 09:03 UTC
