### ISSUE TITLE
SymbolServer must be imported into Main before LanguageServerInstance can be successfully run

### ISSUE THREAD

**Issue by ExpandingMan** [julia-vscode/LanguageServer.jl#750] opened 2020-06-13 02:43 UTC
I'm working on [making sure LanguageServer always gets initialized properly in the appropriate environment](https://github.com/ExpandingMan/LSPNeovim.jl).

I'm often discovering the following behavior: the `LanguageServerInstance` seems to start fine.  After a few minutes, when I'd normally see the "receiving language from SymbolServer" message, I instead get the following (prior messages included here also, apologies for the terrible formatting)
```
"[ Info: Activating LSPNeovim environment\n"
" Activating environment at `~/.cache/nvim/nvim_lsp/LSPNeovim/Project.toml`\n"
'┌ Info: Initializing Language Server\n│   pwd() = "/home/expandingman/.julia/dev/LSPNeovim/bin"\n│   env = "/home/expandingman/.julia/dev/LSPNeovim/bin/.."\n└   depot = "/home/expandingman/.julia"\n'
"ERROR: "
"UndefVarError: SymbolServer not defined"
"\nStacktrace:"
"\n"
" [1] "
"deserialize_module"
"("
"::"
"Serialization"
".Serializer{IOStream}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:956\n [2] handle_deserialize(::Serialization.Serializer{IOStream}, ::Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:855\n [3] deserialize(::Serialization.Serializer{IOStream}"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [4] deserialize_datatype(::Serialization.Serializer{IOStream}, ::Bool"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:1251\n [5] handle_deserialize(::Serialization.Serializer{"
"IOStream}, ::Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:826\n [6] deserialize(::"
"Serialization.Serializer{IOStream}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773"
"\n [7] handle_deserialize(::Serialization."
"Serializer{IOStream}, ::Int32"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:833\n [8] deserialize("
"::Serialization.Serializer{IOStream}) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [9] handle_deserialize"
"(::Serialization.Serializer{IOStream}, ::"
"Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:879\n [10] "
"deserialize(::Serialization.Serializer"
"{IOStream}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773"
"\n [11] "
"deserialize"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:760 [inlined]\n [12] #25 at "
"/home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:171 [inlined]\n [13] "
"open(::SymbolServer."
'var"#25#26", ::String; '
"kwargs"
"::Base.Iterators.Pairs{"
"Union{}"
",Union{},Tuple{},NamedTuple{"
"("
")"
",Tuple{}}}) at ./io.jl:325\n [14] open at "
"./io.jl:323 [inlined]\n [15] load_package_from_cache_into_store!(::SymbolServer"
".SymbolServerInstance, ::Base.UUID, ::"
"Dict{Base.UUID,Pkg.Types."
"PackageEntry}, ::Dict{Symbol,SymbolServer.ModuleStore}"
") at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:170\n [16] load_project_packages_into_store!"
"(::SymbolServer.SymbolServerInstance, ::String, ::Dict"
"{Symbol,SymbolServer.ModuleStore}) at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:142\n [17] "
"getstore(::SymbolServer.SymbolServerInstance, ::String, ::LanguageServer."
'var"#2#4"{LanguageServer.LanguageServerInstance}, ::'
"Nothing) at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:100\n [18] macro expansion at /home/expandingman/.julia/packages/LanguageServer/mpNvN/src/languageserverinstance.jl:157 [inlined]\n [19] "
'(::LanguageServer.var"#1#3"{LanguageServer.LanguageServerInstance})'
"() at ./task.jl:356\n"
"┌ Warning: Tried to load Pkg but failed to load from disc, re-caching.\n└ @ SymbolServer ~/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:179\n"
"ERROR: "
"UndefVarError: SymbolServer not defined"
"\nStacktrace:\n [1] deserialize_module(::Serialization."
"Serializer{IOStream}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:956\n [2] handle_deserialize(::Serialization.Serializer"
"{IOStream}, ::Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:855\n [3] deserialize(::Serialization.Serializer"
"{IOStream}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [4] deserialize_datatype(::"
"Serialization.Serializer{IOStream}, ::Bool) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:1251\n [5] handle_deserialize(::Serialization."
"Serializer{IOStream}, ::Int32) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:826\n [6] deserialize(::Serialization"
".Serializer{IOStream}) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [7] "
"handle_deserialize(::Serialization.Serializer{"
"IOStream}, ::Int32)"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:833\n"
" [8] deserialize(::Serialization"
".Serializer{IOStream}"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n"
" [9] handle_deserialize(::Serialization"
".Serializer{IOStream}"
", ::Int32)"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:879\n [10] "
"deserialize(::Serialization."
"Serializer{IOStream}"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n"
" [11] deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:760 [inlined]\n"
" [12] #25 at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:171 [inlined]\n"
' [13] open(::SymbolServer.var"#25#26", ::String; kwargs::'
"Base.Iterators.Pairs{Union{},Union{},Tuple{},"
"NamedTuple{(),Tuple{}}}) at ./io.jl:325"
"\n [14] open at ./io.jl:323 [inlined]\n [15] load_package_from_cache_into_store!"
"(::SymbolServer.SymbolServerInstance"
", ::Base.UUID"
", ::Dict{Base"
".UUID,Pkg.Types"
".PackageEntry}, "
"::Dict{"
"Symbol,SymbolServer"
".ModuleStore})"
" at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:170\n [16] "
"load_project_packages_into_store!(::SymbolServer"
".SymbolServerInstance, ::"
"String, ::Dict"
"{Symbol,SymbolServer"
".ModuleStore}) at "
"/home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:142\n [17] "
"getstore(::SymbolServer"
".SymbolServerInstance, ::"
"String, ::"
"LanguageServer.var"
'"#2#4"{LanguageServer.'
"LanguageServerInstance}, ::"
"Nothing) at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:100"
"\n [18] macro expansion at /home/expandingman/.julia/packages/LanguageServer/mpNvN/src/languageserverinstance.jl:157"
" [inlined]\n [19] "
'(::LanguageServer.var"#1#3"{LanguageServer.LanguageServerInstance})('
") at ./task.jl:356\n"
"┌ Warning: Tried to load StaticLint but failed to load from disc, re-caching.\n└ @ SymbolServer ~/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:179\n"
"ERROR: "
"UndefVarError: SymbolServer not defined"
"\nStacktrace:\n"
" [1] deserialize_module("
"::Serialization.Serializer"
"{IOStream})"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:956\n"
" [2] handle_deserialize(::"
"Serialization.Serializer{"
"IOStream}, ::"
"Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:855"
"\n [3] deserialize(::"
"Serialization.Serializer"
"{IOStream})"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [4] "
"deserialize_datatype(::Serialization"
".Serializer{IOStream}"
", ::Bool)"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:1251\n"
" [5] handle_deserialize(::Serialization"
".Serializer{IOStream}"
", ::Int32"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:826"
"\n [6] deserialize(::"
"Serialization.Serializer{IOStream}"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n"
" [7] handle_deserialize(::"
"Serialization.Serializer{IOStream"
"}, ::Int32"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:833"
"\n [8] deserialize(::"
"Serialization.Serializer{"
"IOStream}) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [9] "
"handle_deserialize(::Serialization.Serializer"
"{IOStream}, "
"::Int32) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:879\n [10] "
"deserialize(::Serialization.Serializer"
"{IOStream})"
" at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [11] "
"deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:760 [inlined]\n"
" [12] #25 at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:171 [inlined]"
"\n [13] open("
"::SymbolServer."
'var"#25#26", ::'
"String; kwargs::"
"Base.Iterators.Pairs{Union{},"
"Union{},Tuple{}"
",NamedTuple{("
"),Tuple{"
"}}})"
" at ./io.jl:325\n"
" [14] open at "
"./io.jl:323 [inlined]\n [15] "
"load_package_from_cache_into_store!(::"
"SymbolServer.SymbolServerInstance, "
"::Base.UUID"
", ::Dict{"
"Base.UUID,"
"Pkg.Types.PackageEntry"
"}, ::Dict"
"{Symbol,"
"SymbolServer.ModuleStore})"
" at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:170\n"
" [16] load_project_packages_into_store!(::"
"SymbolServer.SymbolServerInstance, "
"::String, ::"
"Dict{Symbol,"
"SymbolServer.ModuleStore}"
") at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:142"
"\n [17] getstore("
"::SymbolServer.SymbolServerInstance"
", ::String, ::"
'LanguageServer.var"#2#4"'
"{LanguageServer.LanguageServerInstance}"
", ::Nothing"
") at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:100"
"\n [18] macro expansion at /home/expandingman/.julia/packages/LanguageServer/mpNvN/src/languageserverinstance.jl:157"
" [inlined]\n [19] "
'(::LanguageServer.var"#1#3"{LanguageServer.LanguageServerInstance})('
") at ./task.jl:356\n"
"┌ Warning: Tried to load LanguageServer but failed to load from disc, re-caching.\n└ @ SymbolServer ~/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:179\n"
"ERROR: "
"UndefVarError: SymbolServer not defined"
"\nStacktrace:\n [1] "
"deserialize_module(::Serialization"
".Serializer{IOStream"
"}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:956"
"\n [2] handle_deserialize(::Serialization"
".Serializer{IOStream}, "
"::Int32) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:855\n [3] "
"deserialize(::Serialization.Serializer{"
"IOStream}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773"
"\n [4] deserialize_datatype(::"
"Serialization.Serializer{IOStream}, "
"::Bool) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:1251"
"\n [5] handle_deserialize(::Serialization"
".Serializer{IOStream}, "
"::Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:826"
"\n [6] deserialize(::Serialization"
".Serializer{IOStream}"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [7] "
"handle_deserialize(::Serialization."
"Serializer{IOStream}, ::"
"Int32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:833"
"\n [8] deserialize(::Serialization."
"Serializer{IOStream}) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [9] handle_deserialize"
"(::Serialization.Serializer{"
"IOStream}, ::Int32"
") at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:879\n"
" [10] deserialize(::Serialization."
"Serializer{IOStream}) at "
"/buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:773\n [11] "
"deserialize at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/Serialization/src/Serialization.jl:760 [inlined]\n [12] #25"
" at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:171 [inlined]\n [13] "
"open(::SymbolServer."
'var"#25#26", ::String'
"; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at ./io.jl:325"
"\n [14] open at ./io.jl:323 [inlined]\n [15] "
"load_package_from_cache_into_store!(::"
"SymbolServer.SymbolServerInstance, ::"
"Base.UUID, ::"
"Dict{Base.UUID"
",Pkg.Types.PackageEntry"
"}, ::Dict"
"{Symbol,SymbolServer."
"ModuleStore}) at "
"/home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:170\n [16] "
"load_project_packages_into_store!(::SymbolServer.SymbolServerInstance"
", ::String, ::Dict"
"{Symbol,SymbolServer.ModuleStore})"
" at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:142\n [17] getstore("
"::SymbolServer.SymbolServerInstance, ::String, ::"
'LanguageServer.var"#2#4"{LanguageServer.'
"LanguageServerInstance}, ::Nothing) at /home/expandingman/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:100"
"\n [18] macro expansion at /home/expandingman/.julia/packages/LanguageServer/mpNvN/src/languageserverinstance.jl:157 [inlined]"
'\n [19] (::LanguageServer.var"#1#3"{LanguageServer.LanguageServerInstance})() at ./task.jl:356'
"\n"
"┌ Warning: Tried to load SymbolServer but failed to load from disc, re-caching.\n└ @ SymbolServer ~/.julia/packages/SymbolServer/vTGsB/src/SymbolServer.jl:179\n"
"[ Info: Received new data from Julia Symbol Server.\n"
```

You can still see the "new data from Symbol Server" near the end.  The bizarre thing is that all of these packages are indeed present, and the manifest works just fine.  Note that I got here by passing `/home/expandingman/.julia/dev/LSPNeovim/bin/..` to the environment path in `LanguageServerInstance`, and there is indeed a manifest there.

**Comment by non-Jedi** [comment] 2020-06-13 02:58
Could you try adding `import SymbolServer` to the run.jl script? The error messages make me suspect this is a duplicate of https://github.com/julia-vscode/SymbolServer.jl/issues/54.

**Comment by ExpandingMan** [comment] 2020-06-13 17:52
Yup, that does it.  Man, that is one seriously bizarre bug, I don't even understand how this possibly fixes it.

**Comment by non-Jedi** [comment] 2020-06-13 18:02
Cool I'm going to leave this one open since the problem is probably in how the language server spawns the symbol server process rather than in SymbolServer.jl itself.

**Comment by davidanthoff** [comment] 2020-06-13 19:28
See my comments in the other issue, short of it is that I think we should get https://github.com/julia-vscode/SymbolServer.jl/pull/155 ready for merge, and then this problem should go away (and whole bunch of other problems as well).

**Comment by pfitzseb** [comment] 2022-03-14 15:13
I don't think so.

**Closed by pfitzseb** 2022-03-14 15:13 UTC
Labels: bug, non-vscode
