### ISSUE TITLE
MethodError: no method matching Union{Int64, String}(::String)

### ISSUE THREAD

**Issue by yuntan** [julia-vscode/LanguageServer.jl#757] opened 2020-06-14 22:48 UTC
LanguageServer crashing on start. May be related to #651 but the stacktrace is different.

```
ERROR: LoadError: MethodError: no method matching Union{Int64, String}(::String)

Stacktrace: 
 [1] LanguageServer.InitializeParams ( :: Dict{ String,Any}) at /home/tokuyuuto/.julia/packages/LanguageServer/qudfd/src/protocol/initialize.jl:111
 [2] dispatch_msg(::JSONRPC.JSONRPCEndpoint, ::JSONRPC.MsgDispatcher, ::Dict{String,Any}) at /home/tokuyuuto/.julia/packages/JSONRPC/nJmHs/src/typed.jl:61
 [3] run(::LanguageServerInstance) at /home/tokuyuuto/.julia/packages/LanguageServer/qudfd/src/languageserverinstance.jl:305
 [4] top-level scope at /dev/fd/3:9
 [5] include(::Module, ::String) at ./Base.jl:377
 [6] exec_options(::Base.  JLOptions) at ./client.jl:288
 [7] _start() at ./client.jl:484
in expression starting at /dev/fd/3:9
```

v 3.1.0
coc.nvim
julia 1.4.0

**Comment by yuntan** [comment] 2020-06-14 23:45
Testing 194e2d9522269caf6600160aec993155b9ee3006, and the issue has resolved. #688

**Comment by non-Jedi** [comment] 2020-06-15 12:12
Duplicate of #651

**Closed by non-Jedi** 2020-06-15 12:12 UTC
Labels: bug, non-vscode
