### ISSUE TITLE
No autocomplete inside user Packages

### ISSUE THREAD

**Issue by lukasgrunwald** [julia-vscode/LanguageServer.jl#1099] opened 2022-06-03 10:16 UTC
I'm unable to get autocomplete (documentation on hover etc.) for functions added to a local package

Steps to reproduce:
- New julia module with `julia> ] generate MyPackage.jl`
- Open `MyPackage.jl` folder with VSCode and choose the folder as the julia environment 
- Add a new function `documented_func` inside the `src/MyPackage.jl` module (with a documentation) and export it
- Create a new file inside of the `src` folder and load the module with `using MyPackage`
- `documented_func` will not be recognized, nor have a documentation even after restarting VSCode/Language-Server.

Is this the intended behavior, or am I doing something wrong? 

Versioninfo: 
- Julia-VSCode - v1.6.17
- `julia> versioninfo()`
Julia Version 1.7.3
Commit 742b9abb4d (2022-05-06 12:58 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, tigerlake)
Environment:
  JULIA_NUM_THREADS = 8

*Note: I'm also loading Revise via `startup.jl` if this is relevant*

**Comment by fredrikekre** [comment] 2022-06-03 10:29
Probably a variant or duplicate of https://github.com/julia-vscode/LanguageServer.jl/issues/988

**Closed** 2022-06-03 13:51 UTC
