### ISSUE TITLE
How to search modules under a custom LOAD_PATH.

### ISSUE THREAD

**Issue by AtsushiSakai** [julia-vscode/LanguageServer.jl#885] opened 2021-02-09 08:54 UTC
Hi. Thank you for great OSS. I'm using this everyday.

I have a question about how to search modules under a custom LOAD_PATH.

I'm using a custom LOAD_PATH for searching my local modules like:
> push!(LOAD_PATH, /path/to/local/module/dir)

Is there any way for the language server to recognize the local modules under the custom LOAD_PATH?

**Comment by davidanthoff** [comment] 2021-02-09 18:18
Short version: not at the moment. I'm closing this as a duplicate of https://github.com/julia-vscode/julia-vscode/issues/307.

**Closed by davidanthoff** 2021-02-09 18:18 UTC
