### ISSUE TITLE
Custom modules not loaded in my path

### ISSUE THREAD

**Issue by ppasquet** [julia-vscode/LanguageServer.jl#1165] opened 2022-10-12 13:01 UTC
I have two modules in two separate files: 

`A.jl`
```
module A

struct Foo
    bar::Integer
end

function create()::Foo
    Foo(1)
end

end
```

`B.jl`
```
module B

using ..A

function test()::Integer
    return -1
end

A.create()
test()

end
```

In the Julia REPL, I can `include("A.jl")` and then `include("B.jl")` and it works. 

However, VS Code doesn't add the content of `A.jl` in the path. For instance, in `B.jl` I can't jump to the definition of `A.create()` and nothing happens when I hover it (whereas I can jump to the definition of / hover `test()`, which is defined in the same file / module).

**Comment by fredrikekre** [comment] 2022-10-12 13:04
So there is nothing linking these files together? I don't think that is expected to work then.

**Comment by ppasquet** [comment] 2022-10-12 13:09
@fredrikekre You're right - it works when I add `include("A.jl")` just before `using ..A`.

**Comment by davidanthoff** [comment] 2022-10-15 14:22
You could probably add a third file that includes both A and B, and I think (not entirely sure, though) the LS should at that point understand the link.

I'm closing for now, as this is kind of by design. If my suggestion doesn't work, please reopen!

**Closed by davidanthoff** 2022-10-15 14:22 UTC
